---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: CentOS Kernel Cleanup
      command: "package-cleanup --oldkernels --count=2 -y"
      when:
        ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: CentOS package cleanup
      yum:
        autoremove: true
      when:
        ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Ubuntu package cleanup
      apt:
        autoremove: true
        autoclean: true
      when:
        ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
