---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: CentOS Kernel Cleanup
      command: "package-cleanup --oldkernels --count=2 -y"
      when: ansible_os_family == "RedHat"

    - name: CentOS package cleanup
      yum:
        autoremove: true
      when: ansible_os_family == "RedHat"

    - name: Ubuntu package cleanup
      apt:
        autoremove: true
        autoclean: true
      when: ansible_os_family == "Debian"
