---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: CentOS check if reboot needed
      command: needs-restarting -r
      register: reboot_required
      ignore_errors: true
      changed_when: true
      when:
        ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Reboot CentOS if check was successful
      shell: (sleep 5; shutdown -r now "CentOS updates triggered") &
      async: 30
      poll: 0
      ignore_errors: true
      notify:
        - waiting for server to come back
      when: ansible_os_family == "RedHat" and reboot_required.rc == 1

    - name: Ubuntu check if reboot is needed and reboot
      shell: (sleep 5; shutdown -r now "Debian/Ubuntu updates triggered") &
      args:
        removes: /var/run/reboot-required
      async: 30
      poll: 0
      ignore_errors: true
      notify:
        - waiting for server to come back
      when: ansible_os_family == "Debian"

  handlers:
    - name: waiting for server to come back
      wait_for_connection:
        delay: 10
