--- 
- hosts: all
  become: yes
  tasks:
    - name: CentOS check if reboot needed
      command: needs-restarting -r 
      register: reboot_required
      ignore_errors: True
      changed_when: False
      when:
        ansible_distribution == 'CentOS'

    - name: Reboot CentOS if check was successful
      shell: (sleep 5; shutdown -r now "CentOS updates triggered") &
      async: 30
      poll: 0
      ignore_errors: true
      notify:
        - waiting for server to come back
      when: ansible_distribution == 'CentOS' and reboot_required.rc == 1

    - name: Ubuntu check if reboot is needed and reboot
      shell: (sleep 5; shutdown -r now "Ubuntu updates triggered") &
            removes=/var/run/reboot-required
      async: 30
      poll: 0
      ignore_errors: true
      notify:
        - waiting for server to come back
      when: 
        ansible_distribution == 'Ubuntu'

  handlers:
    - name: waiting for server to come back
      local_action: 
        wait_for host={{ inventory_hostname }} state=started delay=10 timeout=120     
