---
- hosts: all
  become: true
  become_user: root
  tasks:
    # This task updates our CentOS based systems
    - name: CentOS upgrade
      yum:
        update_cache: true
        name: '*'
        state: latest
        update_only: true
      when:
        ansible_distribution == 'CentOS' or  ansible_distribution == 'Red Hat Enterpise Linux'

    # This task updates our Ubuntu based systems
    - name: Ubuntu upgrade
      apt:
        update_cache: true
        upgrade: full
      when:
        ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
