---
- hosts: all
  become: true
  become_user: root
  tasks:
    # This task updates our RHEL based systems
    - name: RHEL upgrade
      yum:
        name: '*'
        update_cache: true
        state: latest
    when: ansible_os_family == "RedHat"

    # This task updates our Debian based systems
    - name: Debian upgrade
      apt:
        update_cache: true
        upgrade: full
    when: ansible_os_family == "Debian"
