---
- hosts: all
  become: true
  become_user: root
  tasks:
    # This task updates our CentOS based systems
    - name: CentOS upgrade
      yum:
        update_cache: true
        name: '*'
        state: latest
        update_only: true
      when:
        ansible_distribution == 'CentOS'

    # This task updates our Ubuntu based systems
    - name: Ubuntu upgrade
      apt:
        update_cache: yes
        upgrade: dist
      when:
        ansible_distribution == 'Ubuntu'
